[project]
authors = ["Jermiah Joseph <jermiahjoseph98@gmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "Adv360-Pro-ZMK"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]
make.cmd = "make"
make.inputs = [
  "config/west.yml",
  "config/adv360_left.keymap",
  "config/adv360_right.keymap",
  "config/adv360.keymap",
  "Dockerfile",
  "bin/build.sh",
  "bin/get_version.sh",
]
make.description = "Builds the adv360 firmware and generates firmware files in the firmware/ directory"

generate_keymap.cmd = "keymap --config keymap-drawer/config.yaml parse --columns 18 --zmk-keymap config/adv360.keymap > keymap-drawer/adv360_keymap.yaml"
generate_keymap.description = "generates a keymap yaml for the keymap-drawer"
generate_keymap.inputs = ["config/adv360.keymap", "keymap-drawer/config.yaml"]
generate_keymap.outputs = ["keymap-drawer/adv360_keymap.yaml"]

svg.cmd = "keymap --config keymap-drawer/config.yaml draw -s base keypad -o keymap-drawer/adv360_keymap-map.svg keymap-drawer/adv360_keymap.yaml"
svg.description = "generates a keymap svg"
svg.depends_on = ["generate_keymap"]
svg.inputs = ["keymap-drawer/adv360_keymap.yaml", "keymap-drawer/config.yaml"]
svg.outputs = ["keymap-drawer/adv360_keymap-map.svg"]

[target.unix.tasks]
flash.cmd = "./bin/flashadv.sh"
flash.description = "mounts the flash drive"
flash.depends_on = ["make"]

port.cmd = "cat firmware/latest-left.uf2 > ./Volumes/ADV360PRO/left.uf2"
port.description = "copies the latest firmware to the flash drive"
port.depends_on = ["flash"]

# port_right.cmd = "cat firmware/latest-right.uf2 > ./Volumes/ADV360PRO/right.uf2"
# port_right.description = "copies the latest firmware to the flash drive"
# port_right.depends_on = ["flash"]

run = { depends-on = [
  'port',
  'svg',
], description = "flashes the adv360 and generates the svg" }


[dependencies]
python = ">=3.13.0,<4"

[pypi-dependencies]
keymap-drawer = ">=0.18.1, <0.19"
